### ISSUE TITLE
Reorganizing DX7 patches

### ISSUE THREAD

**Issue by jdduncan** [msg/g2ools#1]
Hi,

I have some pch2 files that have been converted from DX7 files, but I do not have the original DX7 sources.  I'd like to reorganize them: take some variations from one patch and some variations from a different one, then save them together as one.  Is there a way to use g2ools to do this?

**Comment by msg** [comment]
Outside of creating a custom app to do it, I would recommend a patch librarian for a dx7.  Generate the syx files and convert that way.  Otherwise, you would have to modify the dx2g2.py converter to accomplish that task.  I also had ideas of merging some of the nm1 patches into variations as well.
