### ISSUE TITLE
g2ools 1.5 converts LFO master osc. to audio frequency osc.

### ISSUE THREAD

**Issue by jdduncan** [msg/g2ools#3]
For example, in http://www.cim.mcgill.ca/~clark/nordmodularbook/patches/Juno6.pch

The module labeled "26-241 BPM" is a master LFO in the original patch, and becomes a master oscillator in the G2 patch. It seems that it should be some sort of LFO.

**Comment by msg** [comment]
That is correct.  The models for the conversion were built specifically by a guy named 3phase on electro-music.com g2 forum to handle cases not possible by the current g2 modules.  There is also optimizations using different modules to decrease cpu and memory usage.  I believe it is to control the g2 slave modules the same as would be on a nm1.
